print('')
print('')
print('⊂_ヽ')
print('　 ＼＼ Λ＿Λ')
print('　　 ＼(　ˇωˇ)')
print('　　　 >　⌒ヽ')
print('　　　/ 　 へ＼')
print('　　 /　　/　＼＼')
print('　　 ﾚ　ノ　　 ヽ_つ')
print('　　/　/')
print('　 /　/|')
print('　(　(ヽ')
print('　|　|、＼')
print('　| 丿 ＼ ⌒)')
print('　| |　　) /')
print('`ノ )　　Lﾉ')
print('(_／')